//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkerWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Information
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public string Post { get; set; }
        public int Rank { get; set; }
        public string City { get; set; }
        public int WorkPhone { get; set; }
        public System.DateTime DateofBirth { get; set; }
        public string Gender { get; set; }
    }
}
